/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package words.utils;

import java.util.Arrays;
import java.util.HashSet;

/**
 *
 * @author xavi
 */
public class StopWords {

    private static HashSet<String> es = null;
    private static HashSet<String> es_articles = null;

    public static boolean spanish_articles(String word) {
        if (es_articles == null) {
            String[] tmp = {
                "un", "una", "unos", "unas",
                "el", "la", "los", "las"
            };
            es_articles = new HashSet<String>(Arrays.asList(tmp));
        }

        return es_articles.contains(word.toLowerCase());
    }

    public static boolean spanish(String word) {
        if (es == null) {
            String[] tmp = {
                "un",
                "una",
                "unas",
                "unos",
                "uno",
                "sobre",
                "todo",
                "también",
                "tras",
                "otro",
                "algún",
                "alguno",
                "alguna",
                "algunos",
                "algunas",
                "ser",
                "es",
                "soy",
                "eres",
                "somos",
                "sois",
                "estoy",
                "esta",
                "estamos",
                "estais",
                "estan",
                "como",
                "en",
                "para",
                "atras",
                "porque",
                "estado",
                "estaba",
                "ante",
                "antes",
                "siendo",
                "ambos",
                "pero",
                "por",
                "poder",
                "puede",
                "puedo",
                "podemos",
                "podeis",
                "pueden",
                "fui",
                "fue",
                "fuimos",
                "fueron",
                "hacer",
                "hago",
                "hace",
                "hacemos",
                "haceis",
                "hacen",
                "cada",
                "fin",
                "incluso",
                "primero",
                "desde",
                "conseguir",
                "consigo",
                "consigue",
                "consigues",
                "conseguimos",
                "consiguen",
                "ir",
                "voy",
                "va",
                "vamos",
                "vais",
                "van",
                "vaya",
                "gueno",
                "ha",
                "tener",
                "tengo",
                "tiene",
                "tenemos",
                "teneis",
                "tienen",
                "el",
                "la",
                "lo",
                "las",
                "los",
                "su",
                "aqui",
                "mio",
                "tuyo",
                "ellos",
                "ellas",
                "nos",
                "nosotros",
                "vosotros",
                "vosotras",
                "si",
                "dentro",
                "solo",
                "solamente",
                "saber",
                "sabes",
                "sabe",
                "sabemos",
                "sabeis",
                "saben",
                "ultimo",
                "largo",
                "bastante",
                "haces",
                "muchos",
                "aquellos",
                "aquellas",
                "sus",
                "entonces",
                "tiempo",
                "verdad",
                "verdadero",
                "verdadera",
                "cierto",
                "ciertos",
                "cierta",
                "ciertas",
                "intentar",
                "intento",
                "intenta",
                "intentas",
                "intentamos",
                "intentais",
                "intentan",
                "dos",
                "bajo",
                "arriba",
                "encima",
                "usar",
                "uso",
                "usas",
                "usa",
                "usamos",
                "usais",
                "usan",
                "emplear",
                "empleo",
                "empleas",
                "emplean",
                "ampleamos",
                "empleais",
                "valor",
                "muy",
                "era",
                "eras",
                "eramos",
                "eran",
                "modo",
                "bien",
                "cual",
                "cuando",
                "donde",
                "mientras",
                "quien",
                "con",
                "entre",
                "sin",
                "trabajo",
                "trabajar",
                "trabajas",
                "trabaja",
                "trabajamos",
                "trabajais",
                "trabajan",
                "podria",
                "podrias",
                "podriamos",
                "podrian",
                "podriais",
                "yo",
                "aquel"};
            es = new HashSet<String>(Arrays.asList(tmp));
        }

        return es.contains(word.toLowerCase());
    }
}
